vezeeta/accounts/urls.py
from django.urls import path
# from django.urls.resolvers import URLPattern
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views


app_name='accounts'

urlpatterns  = [

path('', views.doctors_list, name='doctors_list'),
path('login/',views.user_login, name='login' ),
path('myprofile/' , views.myprofile, name = 'myprofile'),
path('update_profile/', views.updat_profile , name= 'update_profile' ),
path('signup/', views.signup , name='signup'),
path('<slug:slug>/', views.doctor_detail, name='doctor_detail'),



]

vezeeta/vezeeta/urls.py
from accounts.views import doctors_list
from django import urls
import accounts
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('',include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
]
if settings.DEBUG is True:
    urlpatterns +=  static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

vezeeta/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.db.models.fields import CharField, SlugField, TextField
from django.db.models.fields.related import OneToOneField
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.db import migrations
from PIL import Image
from django.db.models.signals import post_save
from django.utils.text import slugify


# Create your models here.
TYPE_OF_PERSON=(
    ('M' , 'Male'),
    ('F', 'Female'),
)
class Profile(models.Model):

    DOCTOR_IN = ( 
    ("جلديه", "جلديه"), 
    ("اسنان", "اسنان"), 
    ("نفسي", "نفسي"), 
    ("اطفال حديثي الولاده", "اطفال حديثي الولاده"), 
    ("مخ واعصاب", "مخ واعصاب"), 
    ("عظام", "عظام"), 
    ("نسا وتوليد", "نساوتوليد"), 
    ("انف واذن وحنجره", "انف واذن وحنجره"), 
    ("قلب واوعيه دمويه", "قلب واوعيه دمويه"), 
    ("امراض دم", "امراض دم"), 
    ("اورام", "اورام"), 
    ("بطانه", "بطانه"), 
    ("تخسيس و تغذيه", "تخسيس و تغذيه"), 
    ("جراحه اطفال", "جراحه اطفال"), 
    ("جراحه اورام", "جراحه اورام"), 
    ("جراحه اوعيه دمويه", "جراحه اوعيه دمويه"),
    ("جراحه تجميل", "جراحه تجميل"),
    ("جراحه سمنه ومناظير", "جراحه سمنه ومناظير"),
) 


    user              =models.OneToOneField(User, verbose_name=_(" user "),on_delete=models.CASCADE)
    name              =models.CharField(("name : "),max_length=100,blank=True,null=True)
    subtitle          =models.CharField(("نبذه عنك  : ") , max_length=100,blank=True, null=True)
    address           =models.CharField(("المحافظه :"), max_length=100,blank=True, null=True)
    address_detail    =models.CharField(("العنوان بالتفصيل : "),max_length=100,blank=True, null=True)
    number_phone      =models.IntegerField(("الهاتف : "),blank=True, null=True)
    working_hours     =models.IntegerField(("عدد ساعات العمل :"),blank=True, null=True)
    wating_time       =models.IntegerField(("مده النتظار : "),blank=True, null=True)
    who_i             =models.TextField(("Who Iam : "), max_length=250,blank=True, null=True)
    price             =models.IntegerField(("Price : "),blank=True, null=True)
    facebook          =models.CharField(max_length=100,blank=True, null=True)
    twitter           =models.CharField(max_length=100,blank=True, null=True)
    google            =models.CharField(max_length=100,blank=True, null=True)
    join_new          =models.DateTimeField(("وقت الانضمام :"),auto_now_add=False,blank=True, null=True)
    type_of_person    =models.CharField(("النوع : "),choices=TYPE_OF_PERSON, max_length=50)
    doctor            =models.CharField(("دكتور ؟ "),choices=DOCTOR_IN, max_length=100,blank=True, null=True)
    image             =models.ImageField(("Image : "),upload_to='profile',blank=True,null=True)
    specialist_doctor =models.CharField(("التخصص : "),choices=DOCTOR_IN, max_length=100,blank=True, null=True)
    slug              =SlugField(("slug"),blank=True, null=True)
    
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)






    class Meta:
        verbose_name= _("Profile")
        verbose_name_plural = _("Profiles")


    def __str__(self):
        return '%s' %(self.user.username)


def create_profile(sender , **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])






    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         output_size = (300,300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)


post_save.connect(create_profile , sender=User)

vezeeta/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields
from django.forms.widgets import PasswordInput
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserCreationForms(UserCreationForm):
    username=forms.CharField(label='اسم المستخدم')
    first_name= forms.CharField(label='الاسم الول')
    last_name=forms.CharField(label='الاسم الاخير')
    email = forms.EmailField(label='البريد الالكتروني')
    password1=forms.CharField(label='كلمه المرور' , widget=forms.PasswordInput(), min_length=5)
    password2=forms.CharField(label='تاكيد كلمه المرور',widget=forms.PasswordInput(),min_length=5)

   
    class Meta:
        model = User
        fields = ('username', 'first_name','last_name','email','password1','password2')

class Youssef(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم')
    password = forms.CharField(label='كلمه المرور', widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','password')


class UpdateUserForm(forms.ModelForm):
    first_name= forms.CharField(label='الاسم الول')
    last_name=forms.CharField(label='الاسم الاخير')
    email = forms.EmailField(label='البريد الالكتروني')
    class Meta:
        model = User
        fields= ('first_name' , 'last_name' , 'email')

class UpdateProfileForm(forms.ModelForm):
   
    class Meta:
        model = Profile
        fields= ('name' , 'address', 'address_detail' , 'number_phone'
        , 'working_hours' , 'wating_time', 'who_i' , 'price'
        , 'facebook' , 'twitter', 'google' , 'join_new', 'type_of_person'
        , 'doctor', 'image' ,'specialist_doctor')

vezeeta/accounts/views.py
from accounts.models import Profile
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from .models import Profile
from .forms import UpdateProfileForm, Youssef,UserCreationForms , UpdateUserForm
from django.contrib.auth import authenticate , login
from django.contrib.auth.decorators import login_required
# Create your views here.

def doctors_list(request):
    doctors = User.objects.all()
    return render(request, 'user/doctors_list.html',{
        'doctors':doctors,
})

def doctor_detail(request,slug):
    doctor_detail= Profile.objects.get(slug= slug)
    return render(request , 'user/doctor_detail.html', {
        'doctor_detail': doctor_detail,
    })
#######################################LOGIN################################
def user_login(request):
    if request.method == 'POST':
        form = Youssef()
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request , username=username , password=password)
        if user is not None:
            login(request , user)
            return redirect('accounts:doctors_list')
    else:
        form = Youssef()
    return render(request , 'user/login.html' , {
    'form': form
    })

    ##########################SIGNUP##############################

def signup(request):
    if request.method == "POST":
        form = UserCreationForms(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username , password=password)
            login(request , user)
            return redirect('accounts:doctors_list')
    else:
        form = UserCreationForms(request.POST)
    return render(request , 'user/signup.html', {
        'form':form
    })


#######################################################


def updat_profile(request):
    user_form = UpdateUserForm(instance=request.user)
    profile_form = UpdateProfileForm(instance=request.user)
    if request.method == "POST":
        user_form = UpdateProfileForm(request.POST , instance=request.user)
        profile_form = UpdateUserForm(request.POST ,request.FILES, instance=request.user.profile)
        if user_form.is_valid and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:myprofile')
    return render(request , 'user/update_profile.html', {
        'user_form' : user_form ,
        'profile_form': profile_form,
    })


@login_required()
def myprofile(request):
    return render(request , 'user/myprofile.html', {})

vezeeta/accounts/templates/user/doctor_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">



    <title>Vezeta</title>

    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/themify-icons.css">
    <link rel="stylesheet" href="css/nice-select.css">
    <link rel="stylesheet" href="css/flaticon.css">
    <link rel="stylesheet" href="css/gijgo.css">
    <link rel="stylesheet" href="css/animate.min.css">
    <link rel="stylesheet" href="css/slicknav.css">

    <link rel="stylesheet" href="css/style.css">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>



<div dir="rtl">

{% include 'search.html' %}

<div class="job_details_area">
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="job_details_header">
                <div class="single_jobs white-bg d-flex justify-content-between">
                    <div class="jobs_left d-flex align-items-center">
                        <div >
                            {% if doctor_detail.image %}
                                <img class="img-circle" src="{{doctor_detail.image.url}}" alt="" width="100" height="100">
                                {% else %}
                                <img class="img-circle" src="{% static 'C:\Users\Youssef\Desktop\vezeeta\vezeeta\static\img\candiateds\3.png' %}" alt="" width="100" height="100">
                            {% endif %}
                        </div>
                        <div class="jobs_conetent">
                            <a href="#" ><h4>{{doctor_detail.name}}</h4></a>
                            <div class="links_locat d-flex align-items-center">
                                <div class="location">
                                    <p> <i class="fa fa-map-marker"></i> مصر  , {{doctor_detail.address}}</p>
                                </div>
                                <div class="location">
                                    <p> <i class="fa fa-clock-o"></i>  وقت الانتظار  دقيقه {{doctor_detail.waiting_time}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="jobs_right">
                        <div class="apply_now">
                            <a class="boxed-btn3" href="">حجز كشف</a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="descript_wrap white-bg">
                <div class="single_wrapp">
                    <h3>نبذه عن الدكتور</h3>
                    <p>{{doctor_detail.subtitle}}</p>
                </div>
                <div class="white-card white-card-inner">
                    <div class="single_wrap" style="margin-top: 10px;">
                        <h4>معلومات عن الدكتور</h4>
                        <ul>
                            <p>{{doctor_detail.who_i}}</p>
                        </ul>
                    </div>
                </div>
                <div class="single_wrap">
                    <h4>خدمات الدكتور :</h4>
                    <ul>
                        <p class="tagitem disable-click pull-left mr-4" style="background-color: #f5f5f5;
                        color: #808184;"> استشاري جراحه وتجميل الاسنان 
                        </p>
                        <p class="tagitem disable-click pull-left" style="background-color: #f5f5f5;
                        color: #808184;">استشاري جراحه وتجميل الاسنان 
                        </p>
                    </ul>
                    <br>
                </div>
                <div class="single_wrap">
                    <h4>صور العيادة :</h4>
                            <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                            <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                            <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                    


                </div>
            </div>

    <!-- comments -->
    <div class="section-row">
        <div class="section-title">
            <h2 style="color: brown;">التعليقات (  )</h2>
        </div>

        <div class="post-comments" >

            <!-- comment -->
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="img/avatar.png" alt="">
                </div>
                <div class="media-body " >
                    <div class="media-heading">
                        <h4>اسم الكاتب</h4>
                        <span class="time">تم التعليق في </span>
                    </div>
                    <p>الكومنتات</p>
                    <a href="#" class="reply">الردود ..</a>

                    <!-- comment -->
                    <div class="media">
                        <div class="media-left">
                            <img class="media-object" src="" alt="">
                        </div>
                        <div class="media-body">
                            <div class="media-heading">
                                <h4>محمود عبد الرؤف صبره</h4>
                                <span class="time">تم التعليق فى </span>
                            </div>
                            <p>شكرا جدا واتمنى ان تتصفح باقي المواضيع .....</p>
                        </div>
                    </div>
                    <!-- /comment -->
                </div>
            </div>
            <!-- /comment -->

            <div class="media-heading">
                <h4>لا يوجد تعليقات حتى الأن ..</h4>
            </div>

        </div>
    </div>
    <!-- /comments -->                    
    <div class="apply_job_form white-bg">
        <h4>إترك تعليقك</h4>
        <form method="POST" >

            <div class="row">
                <div class="col-md-6">
                    <div class="input_field">
                        <input type="text"  placeholder=" الإسم">
                        
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input_field">
                        <input type="text"  placeholder=" الإيميل">
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="input_field">
                        <textarea  cols="30" rows="10" placeholder="تعليقك .."></textarea>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="submit_btn">
                        <button class="boxed-btn3 w-100" type="submit">تعليق</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
        </div>
        <div class="col-lg-4">
            <div class="job_sumary">
                <div class="summery_header">
                    <h3>معلومات عن الدكتور </h3>
                </div>
                <div class="job_content">
                    <ul>
                        <li>  انضم إلينا : <span style="color: blue;"></span></li>
                        <li> الكشف : <span style="color: blue;">  {{doctor_detail.price}}جنية</span></li>
                        <li> رقم الهاتف  :<span style="color: blue;"> {{doctor_detail.number_phone}}</span></li>
                        <li>عدد ساعات العمل :<span style="color: blue;">   {{doctor_detail.working_hours}}ساعات </span></li>
                    </ul>
                    
                </div>
            </div>
            <div class="share_wrap d-flex">
                <span>شارك الصفحه :</span>
                <ul>
                    <li><a href="{{doctor_detail.facebook}}"> <i class="fa fa-facebook"></i></a> </li>
                    <li><a href="{{doctor_detail.google}"> <i class="fa fa-google-plus"></i></a> </li>
                    <li><a href="{{doctor_detail.twitter}"> <i class="fa fa-twitter"></i></a> </li>
                    <li><a href=""> <i class="fa fa-envelope"></i></a> </li>
                </ul>
            </div>
            <div class="job_location_wrap">
                <div class="job_lok_inner">
                    <div id="map" style="height: 200px;"></div>         
                    <script>
                        function initMap() {
                        var uluru = {lat: -25.363, lng: 131.044};
                        var grayStyles = [
                            {
                            featureType: "all",
                            stylers: [
                                { saturation: -90 },
                                { lightness: 50 }
                            ]
                            },
                            {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                        ];
                        var map = new google.maps.Map(document.getElementById('map'), {
                            center: {lat: -31.197, lng: 150.744},
                            zoom: 9,
                            styles: grayStyles,
                            scrollwheel:  false
                        });
                        }
                        
                    </script>
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                    
                    </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>


{% endblock body %}

vezeeta/accounts/templates/user/doctors_list.html
{% extends 'base.html'%}
{% load static %}
{% block body %}

<div dir="rtl">
{%  include 'user/search.html' %}
    <!-- job_listing_area_start  -->
    <div class="job_listing_area">
        <div class="container">

            <div class="job_lists">
                <div class="row">
                    {% for doctor in doctors%}

                    <div class="col-lg-10 col-md-10" style="height: 16rem;" >
                        <div class="single_jobs white-bg d-flex justify-content-between">
                 
                            <div class="jobs_left d-flex align-items-center">
                                <div >
                                    {% if doctor.profile.image %}
                                        <img  src="{{ doctor.profile.image.url }}" alt="" width="100" height="100">
                                        {% else %}
                                        <img  src="{% static 'C:\Users\Youssef\Desktop\vezeeta\vezeeta\static\img\candiateds\1.png' %}" alt="" width="100" height="100">
                                
                                    {% endif %}
                                </div>
                                <div class="jobs_conetent">
                                    <a href="{% url 'accounts:doctor_detail' doctor.profile.slug %}"><h5>دكتور {{ doctor.profile.name}}</h5></a>
                                    <h6></h6>
                                    
                                    <div class="links_locat">
                                        <div class="location">
                                            <p> <i class="fas fa-briefcase-medical"></i> دكتور <span style="color: blue;">{{ doctor.profile.doctor }}</span> متخصص في<span style="color: blue;">{{ doctor.profile.specialist_doctor }}</span></p>
                                            <p> <i class="fa fa-map-marker"></i> {{doctor.profile.address_detail}} : address</p>
                                            <p> <i class="fa fa-map-marker"></i> الكشف : <span style="color: blue;">{{ doctor.profile.price }}</span> جنية </p>
                                            <p> <i class="fa fa-clock-o"></i> مدة الانتظار : <span style="color: blue;">Waiting_time</span> ساعه {{ doctor.profile.wating_time }}</p>
                                            <p> <i class="fa fa-clock-o"></i> عدد ساعات العمل : <span style="color: blue;">{{ doctor.profile.working_hours }}</span> ساعه </p>
                                            <p> <i class="fa fa-clock-o"></i>سعر المكالمه العادية  :<span style="color: blue;"> number_phone {{ doctor.profile.number_phone }}</span>  </p>
                                                                                                                                                                                                        

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="boxed-btn3" href="">حجز كشف</a>
                                </div>

                                <div class="rating">
                                    <div class="text-warning">
                                        <!-- to make image category for clinic image -->
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        </div>
                                    <div class="rating" >
                                        <h5>تقييم الدكتور</h5>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
</div>
    <!-- featured_candidates_area_start  -->
    <div class="featured_candidates_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section_title text-center mb-40">
                        <h3>المرشحين المميزين</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="candidate_active owl-carousel">
                        <div class="single_candidates text-center">
                            <div class="thumb">
                                <img class="img-circle " src="{% static 'img/candiateds/2.png' %}" alt="" >
                                
                            </div>
                            <a href="" ><h4 >الاسم</h4></a>
                            <p>  التخصص</p>
                            <div class="best-rating">
                                <div class="text-warning">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        
                                </div>
                                <div class="best-rating" >
                                    <h5>تقييم الدكتور</h5>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- featured_candidates_area_end  -->

{% endblock body %}

vezeeta/accounts/templates/user/login.html
{% extends 'base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div dir="rtl">
    <div class="container">
        <div class="signup">
        <div class="col-md-9">
            <form method="POST" enctype="multipart/form-data">
                <h4 class="auth-header">انشاء حساب جديد</h4>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.username | as_crispy_field }}
                </div>

                <div class="form-group">
                    {{ form.password | as_crispy_field }}
                </div>
                              
                <div class="button-w"><button type="submit" class="btn btn-success ml-5">تسجيل</button>
                </div>
            </form>

        </div>

        </div>

    </div>


</div>

{% endblock body %}

vezeeta/accounts/templates/user/search.html
  <!-- Search -->
  <div class="catagory_area ">
    <div class="container " style="margin-top: 10rem">
                <div class=" single_text">
                    <h2>احجز مع
                        أفضل دكتور في مصر</h3>
                    <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                    <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                    <br>
                </div>
                <form  method="GET" action="">
                <div class="row cat_search" >
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <input type="text" placeholder="إسم الدكتور" >
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-4">
                   
                        <div class="single_input">
                            <select class="wide" >
                                <option value="" >الموقع</option>
                                <option value="المنصوره">المنصوره</option>
                                <option value="الدقي">الدقي</option>
                                <option value="4">Sylet</option>
                            </select>
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <select class="wide" >
                                <option value="">التخصص</option>
                                <option value="جلدية">جلدية</option>
                                <option value="اسنان">اسنان</option>
                                <option value="نفسي">نفسي</option>
                                <option value="اطفال">اطفال حديثي الولادة</option>
                                <option value="مخ">مخ واعصاب</option>
                                <option value="عظام">عظام</option>
                                <option value="نساء">نساء وتوليد</option>
                                <option value="انف">انف واذن وحنجرة</option>
                                <option value="قلب">قلب واوعية دموية</option>
                                <option value="امراض">امراض دم</option>
                                <option value="اورام">اورام</option>
                                <option value="باطنه">باطنه</option>
                                <option value="تخسيس">تخسيس وتغذية</option>
                                <option value="جاطفال">جراحة اطفال</option>
                                <option value="جاورام">جراحة اورام</option>
                                <option value="جاوعيه">جراحة اوعية دموية</option>
                                <option value="جتجميل">جراحة تجميل</option>
                                <option value="سمنه">جراحه سمنة ومناظير </option>
                                </select>
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-12">
                        <div class="job_btn">
                            <input type="submit" class="boxed-btn3" value="ابحث هنا">
                        </div>
                    </div>
    
                </div>
                </form> 
            </div>
        </div>
        <!-- endsearch -->
      